CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	login VARCHAR(60) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE, 
	createDate TIMESTAMP DEFAULT CLOCK_TIMESTAMP()
);