CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	login VARCHAR(60) NOT NULL UNIQUE,
	password VARCHAR(60) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE, 
	createDate TIMESTAMP DEFAULT CLOCK_TIMESTAMP(),
	role_id INTEGER REFERENCES roles(id) NOT NULL,
	city_id INTEGER REFERENCES cities(id) NOT NULL
);